### ISSUE TITLE
Sttripping url

### ISSUE THREAD

**Issue by SBYDeveloper** [OpenTriply/YASGUI.utils#3]
in agular app i have included YASGUI and when i go to the page everything from the url is stripped to /#

the url is /#/sparql

**Comment by wouterbeek** [comment]
@SBYDeveloper Thanks for trying out YASGUI!  It's not entirely clear to me what you're referring to.  Feel free to reopen this issue in case you can give an MWE or Mininum Working Example (i.e., something other developers can try out themselves to see the issue you run into).
